package org.openmbee.mdk.mms.sync.status.ui;

import com.nomagic.magicdraw.core.Application;
import org.openmbee.mdk.mms.actions.DetailedSyncStatusAction;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by igomes on 8/16/16.
 */
public class SyncStatusFrame extends JFrame {
    private JPanel rootPanel;
    private JLabel inMemoryLocalCreatedLabel;
    private JLabel inMemoryLocalUpdatedLabel;
    private JLabel inMemoryLocalDeletedLabel;
    private JLabel persistedLocalCreatedLabel;
    private JLabel persistedLocalUpdatedLabel;
    private JLabel persistedLocalDeletedLabel;
    private JLabel totalLocalCreatedLabel;
    private JLabel totalLocalUpdatedLabel;
    private JLabel totalLocalDeletedLabel;
    private JLabel totalInMemoryLocalChangedLabel;
    private JLabel totalPersistedLocalChangedLabel;
    private JLabel totalLocalChangedLabel;
    private JLabel inMemoryMmsCreatedLabel;
    private JLabel inMemoryMmsUpdatedLabel;
    private JLabel inMemoryMmsDeletedLabel;
    private JLabel persistedMmsCreatedLabel;
    private JLabel persistedMmsUpdatedLabel;
    private JLabel persistedMmsDeletedLabel;
    private JLabel totalMmsCreatedLabel;
    private JLabel totalMmsUpdatedLabel;
    private JLabel totalMmsDeletedLabel;
    private JLabel totalInMemoryMmsChangedLabel;
    private JLabel totalPersistedMmsChangedLabel;
    private JLabel totalMmsChangedLabel;
    private JButton detailsButton;

    public JPanel getRootPanel() {
        return rootPanel;
    }

    public JLabel getInMemoryLocalCreatedLabel() {
        return inMemoryLocalCreatedLabel;
    }

    public JLabel getInMemoryLocalUpdatedLabel() {
        return inMemoryLocalUpdatedLabel;
    }

    public JLabel getInMemoryLocalDeletedLabel() {
        return inMemoryLocalDeletedLabel;
    }

    public JLabel getPersistedLocalCreatedLabel() {
        return persistedLocalCreatedLabel;
    }

    public JLabel getPersistedLocalUpdatedLabel() {
        return persistedLocalUpdatedLabel;
    }

    public JLabel getPersistedLocalDeletedLabel() {
        return persistedLocalDeletedLabel;
    }

    public JLabel getTotalLocalCreatedLabel() {
        return totalLocalCreatedLabel;
    }

    public JLabel getTotalLocalUpdatedLabel() {
        return totalLocalUpdatedLabel;
    }

    public JLabel getTotalLocalDeletedLabel() {
        return totalLocalDeletedLabel;
    }

    public JLabel getTotalInMemoryLocalChangedLabel() {
        return totalInMemoryLocalChangedLabel;
    }

    public JLabel getTotalPersistedLocalChangedLabel() {
        return totalPersistedLocalChangedLabel;
    }

    public JLabel getTotalLocalChangedLabel() {
        return totalLocalChangedLabel;
    }

    public JLabel getInMemoryMmsCreatedLabel() {
        return inMemoryMmsCreatedLabel;
    }

    public JLabel getInMemoryMmsUpdatedLabel() {
        return inMemoryMmsUpdatedLabel;
    }

    public JLabel getInMemoryMmsDeletedLabel() {
        return inMemoryMmsDeletedLabel;
    }

    public JLabel getPersistedMmsCreatedLabel() {
        return persistedMmsCreatedLabel;
    }

    public JLabel getPersistedMmsUpdatedLabel() {
        return persistedMmsUpdatedLabel;
    }

    public JLabel getPersistedMmsDeletedLabel() {
        return persistedMmsDeletedLabel;
    }

    public JLabel getTotalMmsCreatedLabel() {
        return totalMmsCreatedLabel;
    }

    public JLabel getTotalMmsUpdatedLabel() {
        return totalMmsUpdatedLabel;
    }

    public JLabel getTotalMmsDeletedLabel() {
        return totalMmsDeletedLabel;
    }

    public JLabel getTotalInMemoryMmsChangedLabel() {
        return totalInMemoryMmsChangedLabel;
    }

    public JLabel getTotalPersistedMmsChangedLabel() {
        return totalPersistedMmsChangedLabel;
    }

    public JLabel getTotalMmsChangedLabel() {
        return totalMmsChangedLabel;
    }

    public JButton getDetailsButton() {
        return detailsButton;
    }

    public SyncStatusFrame() {
        super("Sync Status");
        setContentPane(rootPanel);
        setLocationRelativeTo(Application.getInstance().getMainFrame());
        pack();
        setMinimumSize(getSize());
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//        setAlwaysOnTop(true);
        detailsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new DetailedSyncStatusAction().actionPerformed(null);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(6, 6, 6, 6);
        rootPanel.add(panel1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Stored in Memory");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Stored in Model");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(label2, gbc);
        persistedLocalCreatedLabel = new JLabel();
        persistedLocalCreatedLabel.setText("1");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(persistedLocalCreatedLabel, gbc);
        persistedLocalUpdatedLabel = new JLabel();
        persistedLocalUpdatedLabel.setText("2");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(persistedLocalUpdatedLabel, gbc);
        persistedLocalDeletedLabel = new JLabel();
        persistedLocalDeletedLabel.setText("3");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(persistedLocalDeletedLabel, gbc);
        persistedMmsCreatedLabel = new JLabel();
        persistedMmsCreatedLabel.setText("4");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(persistedMmsCreatedLabel, gbc);
        persistedMmsUpdatedLabel = new JLabel();
        persistedMmsUpdatedLabel.setText("5");
        gbc = new GridBagConstraints();
        gbc.gridx = 9;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(persistedMmsUpdatedLabel, gbc);
        persistedMmsDeletedLabel = new JLabel();
        persistedMmsDeletedLabel.setText("6");
        gbc = new GridBagConstraints();
        gbc.gridx = 10;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(persistedMmsDeletedLabel, gbc);
        inMemoryLocalCreatedLabel = new JLabel();
        inMemoryLocalCreatedLabel.setText("6");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(inMemoryLocalCreatedLabel, gbc);
        inMemoryLocalUpdatedLabel = new JLabel();
        inMemoryLocalUpdatedLabel.setText("5");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(inMemoryLocalUpdatedLabel, gbc);
        inMemoryLocalDeletedLabel = new JLabel();
        inMemoryLocalDeletedLabel.setText("4");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(inMemoryLocalDeletedLabel, gbc);
        inMemoryMmsCreatedLabel = new JLabel();
        inMemoryMmsCreatedLabel.setText("3");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(inMemoryMmsCreatedLabel, gbc);
        inMemoryMmsUpdatedLabel = new JLabel();
        inMemoryMmsUpdatedLabel.setText("2");
        gbc = new GridBagConstraints();
        gbc.gridx = 9;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(inMemoryMmsUpdatedLabel, gbc);
        inMemoryMmsDeletedLabel = new JLabel();
        inMemoryMmsDeletedLabel.setText("1");
        gbc = new GridBagConstraints();
        gbc.gridx = 10;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(inMemoryMmsDeletedLabel, gbc);
        final JLabel label3 = new JLabel();
        label3.setFont(new Font(label3.getFont().getName(), Font.BOLD, 14));
        label3.setText("Unsynced Local Changes");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridwidth = 5;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setFont(new Font(label4.getFont().getName(), Font.BOLD, 14));
        label4.setText("Unsynced MMS Changes");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 0;
        gbc.gridwidth = 5;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Created");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Updated");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Deleted");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(label7, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Created");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(label8, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Updated");
        gbc = new GridBagConstraints();
        gbc.gridx = 9;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(label9, gbc);
        final JLabel label10 = new JLabel();
        label10.setText("Deleted");
        gbc = new GridBagConstraints();
        gbc.gridx = 10;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(label10, gbc);
        final JLabel label11 = new JLabel();
        label11.setFont(new Font(label11.getFont().getName(), Font.BOLD, label11.getFont().getSize()));
        label11.setText("Total");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(label11, gbc);
        totalLocalCreatedLabel = new JLabel();
        totalLocalCreatedLabel.setFont(new Font(totalLocalCreatedLabel.getFont().getName(), Font.BOLD, totalLocalCreatedLabel.getFont().getSize()));
        totalLocalCreatedLabel.setText("7");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(totalLocalCreatedLabel, gbc);
        totalLocalUpdatedLabel = new JLabel();
        totalLocalUpdatedLabel.setFont(new Font(totalLocalUpdatedLabel.getFont().getName(), Font.BOLD, totalLocalUpdatedLabel.getFont().getSize()));
        totalLocalUpdatedLabel.setText("7");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(totalLocalUpdatedLabel, gbc);
        totalLocalDeletedLabel = new JLabel();
        totalLocalDeletedLabel.setFont(new Font(totalLocalDeletedLabel.getFont().getName(), Font.BOLD, totalLocalDeletedLabel.getFont().getSize()));
        totalLocalDeletedLabel.setText("7");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(totalLocalDeletedLabel, gbc);
        totalMmsCreatedLabel = new JLabel();
        totalMmsCreatedLabel.setFont(new Font(totalMmsCreatedLabel.getFont().getName(), Font.BOLD, totalMmsCreatedLabel.getFont().getSize()));
        totalMmsCreatedLabel.setText("7");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(totalMmsCreatedLabel, gbc);
        totalMmsUpdatedLabel = new JLabel();
        totalMmsUpdatedLabel.setFont(new Font(totalMmsUpdatedLabel.getFont().getName(), Font.BOLD, totalMmsUpdatedLabel.getFont().getSize()));
        totalMmsUpdatedLabel.setText("7");
        gbc = new GridBagConstraints();
        gbc.gridx = 9;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(totalMmsUpdatedLabel, gbc);
        totalMmsDeletedLabel = new JLabel();
        totalMmsDeletedLabel.setFont(new Font(totalMmsDeletedLabel.getFont().getName(), Font.BOLD, totalMmsDeletedLabel.getFont().getSize()));
        totalMmsDeletedLabel.setText("7");
        gbc = new GridBagConstraints();
        gbc.gridx = 10;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(totalMmsDeletedLabel, gbc);
        final JSeparator separator1 = new JSeparator();
        separator1.setOrientation(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridheight = 4;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(separator1, gbc);
        final JSeparator separator2 = new JSeparator();
        separator2.setOrientation(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 0;
        gbc.gridheight = 7;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(separator2, gbc);
        final JSeparator separator3 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.gridwidth = 5;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(separator3, gbc);
        final JSeparator separator4 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 2;
        gbc.gridwidth = 5;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(separator4, gbc);
        final JSeparator separator5 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(separator5, gbc);
        final JSeparator separator6 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 5;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(separator6, gbc);
        final JLabel label12 = new JLabel();
        label12.setFont(new Font(label12.getFont().getName(), Font.BOLD, label12.getFont().getSize()));
        label12.setText("Total");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(label12, gbc);
        totalInMemoryLocalChangedLabel = new JLabel();
        totalInMemoryLocalChangedLabel.setFont(new Font(totalInMemoryLocalChangedLabel.getFont().getName(), Font.BOLD, totalInMemoryLocalChangedLabel.getFont().getSize()));
        totalInMemoryLocalChangedLabel.setText("15");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(totalInMemoryLocalChangedLabel, gbc);
        totalPersistedLocalChangedLabel = new JLabel();
        totalPersistedLocalChangedLabel.setFont(new Font(totalPersistedLocalChangedLabel.getFont().getName(), Font.BOLD, totalPersistedLocalChangedLabel.getFont().getSize()));
        totalPersistedLocalChangedLabel.setText("6");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(totalPersistedLocalChangedLabel, gbc);
        totalLocalChangedLabel = new JLabel();
        totalLocalChangedLabel.setFont(new Font(totalLocalChangedLabel.getFont().getName(), Font.BOLD, totalLocalChangedLabel.getFont().getSize()));
        totalLocalChangedLabel.setText("21");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(totalLocalChangedLabel, gbc);
        final JLabel label13 = new JLabel();
        label13.setFont(new Font(label13.getFont().getName(), Font.BOLD, label13.getFont().getSize()));
        label13.setText("Total");
        gbc = new GridBagConstraints();
        gbc.gridx = 12;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(label13, gbc);
        totalInMemoryMmsChangedLabel = new JLabel();
        totalInMemoryMmsChangedLabel.setFont(new Font(totalInMemoryMmsChangedLabel.getFont().getName(), Font.BOLD, totalInMemoryMmsChangedLabel.getFont().getSize()));
        totalInMemoryMmsChangedLabel.setText("6");
        gbc = new GridBagConstraints();
        gbc.gridx = 12;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(totalInMemoryMmsChangedLabel, gbc);
        totalPersistedMmsChangedLabel = new JLabel();
        totalPersistedMmsChangedLabel.setFont(new Font(totalPersistedMmsChangedLabel.getFont().getName(), Font.BOLD, totalPersistedMmsChangedLabel.getFont().getSize()));
        totalPersistedMmsChangedLabel.setText("15");
        gbc = new GridBagConstraints();
        gbc.gridx = 12;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(totalPersistedMmsChangedLabel, gbc);
        totalMmsChangedLabel = new JLabel();
        totalMmsChangedLabel.setFont(new Font(totalMmsChangedLabel.getFont().getName(), Font.BOLD, totalMmsChangedLabel.getFont().getSize()));
        totalMmsChangedLabel.setText("21");
        gbc = new GridBagConstraints();
        gbc.gridx = 12;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(totalMmsChangedLabel, gbc);
        final JSeparator separator7 = new JSeparator();
        separator7.setOrientation(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 3;
        gbc.gridheight = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(separator7, gbc);
        final JSeparator separator8 = new JSeparator();
        separator8.setOrientation(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 11;
        gbc.gridy = 3;
        gbc.gridheight = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(separator8, gbc);
        final JSeparator separator9 = new JSeparator();
        separator9.setOrientation(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(separator9, gbc);
        final JSeparator separator10 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(separator10, gbc);
        final JSeparator separator11 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 12;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(separator11, gbc);
        final JSeparator separator12 = new JSeparator();
        separator12.setOrientation(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 11;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(separator12, gbc);
        detailsButton = new JButton();
        detailsButton.setText("Details");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(detailsButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
